import type { DashboardPageData } from "./types";

// Today: 2026-05-05
// startDate: 2026-04-21 (14 days ago) → DAY 14 OF 60
// targetEndDate: 2026-06-20 (46 days from now; 60 days total)

const EVENTS = {
  "evt-commit-1": {
    id: "evt-commit-1",
    projectId: "demo-project",
    type: "COMMIT" as const,
    externalId: "a3f9c2d",
    title: "feat(imagery): integrate FLUX.1 model for product photography generation",
    body: null,
    authorName: "Lucas Figueroa",
    authorLogin: "lucasfigueroa0518",
    authorAvatarUrl: "https://avatars.githubusercontent.com/u/1?v=4",
    url: "https://github.com/DanteHelios/helios-dashboards/commit/a3f9c2d",
    occurredAt: new Date("2026-05-04T14:22:00Z"),
    meta: {},
    fetchedAt: new Date("2026-05-04T14:30:00Z"),
  },
  "evt-commit-2": {
    id: "evt-commit-2",
    projectId: "demo-project",
    type: "COMMIT" as const,
    externalId: "b8e1047",
    title: "fix(pipeline): resolve timeout in batch image processor, add retry logic",
    body: null,
    authorName: "Dante Santurian",
    authorLogin: "DanteHelios",
    authorAvatarUrl: "https://avatars.githubusercontent.com/u/2?v=4",
    url: "https://github.com/DanteHelios/helios-dashboards/commit/b8e1047",
    occurredAt: new Date("2026-05-03T11:05:00Z"),
    meta: {},
    fetchedAt: new Date("2026-05-03T11:30:00Z"),
  },
  "evt-pr-2": {
    id: "evt-pr-2",
    projectId: "demo-project",
    type: "PR_MERGED" as const,
    externalId: "47",
    title: "Add Shopify metafield sync for AI-generated product images",
    body: "Syncs generated image URLs back to Local Boy's Shopify store via the Metafields API. Each SKU gets a `custom.ai_image_url` metafield that the theme reads. Tested on 12 SKUs in staging — all updated cleanly.",
    authorName: "Dante Santurian",
    authorLogin: "DanteHelios",
    authorAvatarUrl: "https://avatars.githubusercontent.com/u/2?v=4",
    url: "https://github.com/DanteHelios/helios-dashboards/pull/47",
    occurredAt: new Date("2026-05-02T16:48:00Z"),
    meta: { mergedSha: "c2d9f3a", baseBranch: "main", additions: 312, deletions: 18 },
    fetchedAt: new Date("2026-05-02T17:00:00Z"),
  },
  "evt-issue-1": {
    id: "evt-issue-1",
    projectId: "demo-project",
    type: "ISSUE_CLOSED" as const,
    externalId: "39",
    title: "Image quality below standard for dark-product SKUs",
    body: null,
    authorName: "Lucas Figueroa",
    authorLogin: "lucasfigueroa0518",
    authorAvatarUrl: "https://avatars.githubusercontent.com/u/1?v=4",
    url: "https://github.com/DanteHelios/helios-dashboards/issues/39",
    occurredAt: new Date("2026-04-30T09:14:00Z"),
    meta: { labels: ["bug"], stateReason: "completed" },
    fetchedAt: new Date("2026-04-30T09:30:00Z"),
  },
  "evt-commit-4": {
    id: "evt-commit-4",
    projectId: "demo-project",
    type: "COMMIT" as const,
    externalId: "d7c3e51",
    title: "feat(scheduler): add daily image generation cron with retry logic",
    body: null,
    authorName: "Dante Santurian",
    authorLogin: "DanteHelios",
    authorAvatarUrl: "https://avatars.githubusercontent.com/u/2?v=4",
    url: "https://github.com/DanteHelios/helios-dashboards/commit/d7c3e51",
    occurredAt: new Date("2026-04-29T13:40:00Z"),
    meta: {},
    fetchedAt: new Date("2026-04-29T14:00:00Z"),
  },
  "evt-pr-1": {
    id: "evt-pr-1",
    projectId: "demo-project",
    type: "PR_MERGED" as const,
    externalId: "41",
    title: "Implement SKU catalog import from Local Boy Shopify store",
    body: "Pulls all active products from the Shopify Admin API, maps them to our internal SKU schema, and stores them in the DB. 94 products imported in the first run. Includes a nightly refresh cron.",
    authorName: "Lucas Figueroa",
    authorLogin: "lucasfigueroa0518",
    authorAvatarUrl: "https://avatars.githubusercontent.com/u/1?v=4",
    url: "https://github.com/DanteHelios/helios-dashboards/pull/41",
    occurredAt: new Date("2026-04-27T10:22:00Z"),
    meta: { mergedSha: "e4a8b12", baseBranch: "main", additions: 487, deletions: 42 },
    fetchedAt: new Date("2026-04-27T10:30:00Z"),
  },
  "evt-commit-5": {
    id: "evt-commit-5",
    projectId: "demo-project",
    type: "COMMIT" as const,
    externalId: "f1b2c3d",
    title: "feat(storage): add Vercel Blob integration for generated image delivery",
    body: null,
    authorName: "Dante Santurian",
    authorLogin: "DanteHelios",
    authorAvatarUrl: "https://avatars.githubusercontent.com/u/2?v=4",
    url: "https://github.com/DanteHelios/helios-dashboards/commit/f1b2c3d",
    occurredAt: new Date("2026-04-25T15:55:00Z"),
    meta: {},
    fetchedAt: new Date("2026-04-25T16:00:00Z"),
  },
  "evt-pr-3": {
    id: "evt-pr-3",
    projectId: "demo-project",
    type: "PR_MERGED" as const,
    externalId: "33",
    title: "Set up image generation pipeline with Replicate API",
    body: "Establishes the core pipeline: prompt builder → Replicate API call → image download → Blob upload. Validated end-to-end with 5 test SKUs. p99 latency is 8.2s per image.",
    authorName: "Dante Santurian",
    authorLogin: "DanteHelios",
    authorAvatarUrl: "https://avatars.githubusercontent.com/u/2?v=4",
    url: "https://github.com/DanteHelios/helios-dashboards/pull/33",
    occurredAt: new Date("2026-04-23T12:00:00Z"),
    meta: { mergedSha: "a9c4d71", baseBranch: "main", additions: 623, deletions: 0 },
    fetchedAt: new Date("2026-04-23T12:15:00Z"),
  },
  "evt-issue-2": {
    id: "evt-issue-2",
    projectId: "demo-project",
    type: "ISSUE_CLOSED" as const,
    externalId: "28",
    title: "Define image output specs for Q3 catalog (aspect ratio, resolution, background)",
    body: null,
    authorName: "Lucas Figueroa",
    authorLogin: "lucasfigueroa0518",
    authorAvatarUrl: "https://avatars.githubusercontent.com/u/1?v=4",
    url: "https://github.com/DanteHelios/helios-dashboards/issues/28",
    occurredAt: new Date("2026-04-22T09:00:00Z"),
    meta: { labels: ["spec"], stateReason: "completed" },
    fetchedAt: new Date("2026-04-22T09:15:00Z"),
  },
};

export const DEMO_DATA: DashboardPageData = {
  project: {
    id: "demo-project",
    name: "Q3 Content Engine",
    status: "ACTIVE",
    startDate: new Date("2026-04-21T00:00:00Z"),
    targetEndDate: new Date("2026-06-20T00:00:00Z"),
    completedAt: null,
    accessToken: "demo-token-replace-me-in-prod",
    deckPdfUrl: "/helios-deck.pdf",
    client: { id: "demo-client", name: "Local Boy Outfitters" },
  },

  latestUpdate: {
    id: "update-3",
    projectId: "demo-project",
    windowStart: new Date("2026-04-30T00:00:00Z"),
    windowEnd: new Date("2026-05-04T23:59:00Z"),
    generatedAt: new Date("2026-05-04T07:00:00Z"),
    bullets: {
      bullets: [
        {
          text: "We shipped the Shopify metafield sync, connecting AI-generated product images directly to Local Boy's live catalog — each SKU now gets an updated image URL on every generation run.",
          sources: [{ eventId: "evt-pr-2" }],
        },
        {
          text: "We resolved a quality issue affecting dark-product SKUs, improving contrast and shadow rendering in the FLUX.1 model pipeline.",
          sources: [{ eventId: "evt-issue-1" }],
        },
        {
          text: "We integrated FLUX.1 as the primary image model, replacing the previous Stable Diffusion setup for higher-fidelity product photography outputs.",
          sources: [{ eventId: "evt-commit-1" }],
        },
        {
          text: "The batch image processor now retries failed generations automatically, reducing manual intervention on the daily cron run.",
          sources: [{ eventId: "evt-commit-2" }],
        },
      ],
    },
  },

  historyUpdates: [
    {
      id: "update-2",
      projectId: "demo-project",
      windowStart: new Date("2026-04-25T00:00:00Z"),
      windowEnd: new Date("2026-04-29T23:59:00Z"),
      generatedAt: new Date("2026-04-30T07:00:00Z"),
      bullets: {
        bullets: [
          {
            text: "We completed the SKU catalog import from Local Boy's Shopify store, giving the pipeline a structured list of all 94 active products.",
            sources: [{ eventId: "evt-pr-1" }],
          },
          {
            text: "We deployed the daily image generation cron with retry logic, automating the full creation cycle end to end.",
            sources: [{ eventId: "evt-commit-4" }],
          },
          {
            text: "We added Vercel Blob storage for generated images, establishing a stable CDN-backed delivery layer for the catalog.",
            sources: [{ eventId: "evt-commit-5" }],
          },
        ],
      },
    },
    {
      id: "update-1",
      projectId: "demo-project",
      windowStart: new Date("2026-04-21T00:00:00Z"),
      windowEnd: new Date("2026-04-24T23:59:00Z"),
      generatedAt: new Date("2026-04-25T07:00:00Z"),
      bullets: {
        bullets: [
          {
            text: "We stood up the core image generation pipeline using the Replicate API, validating the full request-to-image flow with 5 test SKUs at 8.2s median latency per image.",
            sources: [{ eventId: "evt-pr-3" }],
          },
          {
            text: "We defined and closed the image output specifications for the Q3 catalog, locking in aspect ratios, resolution targets, and background treatment for all 94 SKUs.",
            sources: [{ eventId: "evt-issue-2" }],
          },
        ],
      },
    },
  ],

  // Last 14 days of repo events, newest first
  recentEvents: [
    EVENTS["evt-commit-1"],
    EVENTS["evt-commit-2"],
    EVENTS["evt-pr-2"],
    EVENTS["evt-issue-1"],
    EVENTS["evt-commit-4"],
    EVENTS["evt-pr-1"],
    EVENTS["evt-commit-5"],
    EVENTS["evt-pr-3"],
    EVENTS["evt-issue-2"],
  ],
};

// Index events by ID so bullets can look up source details
export const DEMO_EVENTS_BY_ID = EVENTS;
